# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'calculator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()



DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\x12\ncalculator\"\'\n\x11\x43\x61lculatorRequest\x12\x12\n\nexpression\x18\x01 \x01(\t\"3\n\x12\x43\x61lculatorResponse\x12\x0e\n\x06result\x18\x01 \x01(\x01\x12\r\n\x05\x65rror\x18\x02 \x01(\t2_\n\x11\x43\x61lculatorService\x12J\n\tCalculate\x12\x1d.calculator.CalculatorRequest\x1a\x1e.calculator.CalculatorResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CALCULATORREQUEST']._serialized_start=32
  _globals['_CALCULATORREQUEST']._serialized_end=71
  _globals['_CALCULATORRESPONSE']._serialized_start=73
  _globals['_CALCULATORRESPONSE']._serialized_end=124
  _globals['_CALCULATORSERVICE']._serialized_start=126
  _globals['_CALCULATORSERVICE']._serialized_end=221
# @@protoc_insertion_point(module_scope)

